<?php
require_once __DIR__.'/includes/app.php'; $u=require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='create'){ $username=trim($_POST['username']??'');$first=trim($_POST['first_name']??'');$last=trim($_POST['last_name']??'');$password=$_POST['password']??'';$role=in_array($_POST['role']??'', ['member','spiess','admin'],true)?$_POST['role']:'member'; if(strlen($username)<3||strlen($password)<8||$first===''||$last===''){flash('danger','Bitte alle Pflichtfelder korrekt ausfüllen.');redirect('/members.php');} try{$st=$pdo->prepare('INSERT INTO users(username,password_hash,first_name,last_name,role) VALUES(?,?,?,?,?)');$st->execute([$username,password_hash($password,PASSWORD_DEFAULT),$first,$last,$role]);flash('success','Benutzer wurde angelegt.');}catch(Throwable $e){flash('danger','Benutzername ist möglicherweise bereits vergeben.');}redirect('/members.php'); }
 if($action==='toggle'){ $id=(int)$_POST['id']; if($id===$u['id']){flash('warning','Den eigenen Admin-Account kannst du hier nicht deaktivieren.');redirect('/members.php');} $st=$pdo->prepare('UPDATE users SET is_active=1-is_active WHERE id=?');$st->execute([$id]);flash('success','Benutzerstatus geändert.');redirect('/members.php'); }
}
$users=$pdo->query('SELECT id,username,first_name,last_name,role,is_active,created_at FROM users ORDER BY is_active DESC,last_name,first_name')->fetchAll(); $pageTitle='Benutzerverwaltung';require __DIR__.'/includes/header.php';?>
<div class="container dashboard-shell"><div class="d-flex justify-content-between align-items-center mb-4"><div><div class="eyebrow">Administration</div><h1 class="section-title h2 mb-0">Benutzer</h1></div><button class="btn btn-brand" data-bs-toggle="modal" data-bs-target="#newUser"><i class="bi bi-person-plus me-1"></i> Mitglied anlegen</button></div><div class="panel p-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Name</th><th>Benutzername</th><th>Rolle</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($users as $m):?><tr><td><strong><?=e($m['first_name'].' '.$m['last_name'])?></strong></td><td><?=e($m['username'])?></td><td><?=e(role_label($m['role']))?></td><td><?=$m['is_active']?'<span class="badge text-bg-success">Aktiv</span>':'<span class="badge text-bg-secondary">Inaktiv</span>'?></td><td class="text-end"><?php if($m['id']!=$u['id']):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$m['id']?>"><button class="btn btn-sm btn-outline-secondary"><?=$m['is_active']?'Deaktivieren':'Aktivieren'?></button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="newUser"><div class="modal-dialog modal-dialog-centered"><form method="post" class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Neuen Benutzer anlegen</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><div class="row g-3"><div class="col-6"><label class="form-label">Vorname</label><input name="first_name" class="form-control" required></div><div class="col-6"><label class="form-label">Nachname</label><input name="last_name" class="form-control" required></div><div class="col-12"><label class="form-label">Benutzername</label><input name="username" class="form-control" required></div><div class="col-12"><label class="form-label">Startpasswort</label><input type="password" minlength="8" name="password" class="form-control" required></div><div class="col-12"><label class="form-label">Rolle</label><select name="role" class="form-select"><option value="member">Mitglied</option><option value="spiess">Spieß / Moderator</option><option value="admin">Administrator</option></select></div></div></div><div class="modal-footer"><button class="btn btn-brand">Benutzer anlegen</button></div></form></div></div><?php require __DIR__.'/includes/footer.php';?>
