<?php
require_once __DIR__.'/includes/app.php';
$u=require_login();$canUpload=can_reopen_protocols();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 try{
  if(!$canUpload)throw new RuntimeException('Nur Schriftführer oder Admin dürfen das Archiv bearbeiten.');
  if(($_POST['action']??'')==='reopen'){
   $q=$pdo->prepare("UPDATE meetings SET status='scheduled',completed_at=NULL,completed_by=NULL,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='completed'");$q->execute([$u['id'],(int)$_POST['meeting_id']]);if(!$q->rowCount())throw new RuntimeException('Protokoll nicht gefunden oder bereits geöffnet.');meeting_audit($pdo,(int)$_POST['meeting_id'],$u['id'],'reopened','Aus Archiv geöffnet');flash('success','Protokoll wurde wieder geöffnet.');
  } elseif(($_POST['action']??'')==='upload'){
   $files=$_FILES['pdf']??null;if(!$files||!is_array($files['name']))throw new RuntimeException('Bitte mindestens ein PDF auswählen.');$dir=dirname(__DIR__).'/strahlemaennkes-private/protocol-documents';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Archivordner konnte nicht erstellt werden.');$add=$pdo->prepare('INSERT INTO protocol_documents(title,document_date,note,storage_name,original_name,uploaded_by) VALUES(?,?,?,?,?,?)');$count=0;
   foreach($files['name'] as $i=>$name){if(($files['error'][$i]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;if(($files['error'][$i]??0)!==UPLOAD_ERR_OK)throw new RuntimeException('Ein PDF konnte nicht hochgeladen werden.');$tmp=(string)$files['tmp_name'][$i];if(!is_uploaded_file($tmp)||(int)$files['size'][$i]>20*1024*1024)throw new RuntimeException('PDF ungültig oder größer als 20 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp);$head=file_get_contents($tmp,false,null,0,5);if($mime!=='application/pdf'||$head!=="%PDF-")throw new RuntimeException('Es sind nur echte PDF-Dateien erlaubt.');$date=(string)($_POST['date'][$i]??'');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Bitte für jedes PDF ein Datum angeben.');$title=trim((string)($_POST['title'][$i]??''));if($title==='')$title=pathinfo((string)$name,PATHINFO_FILENAME);$storage=date('Ymd-His').'-'.bin2hex(random_bytes(8)).'.pdf';if(!move_uploaded_file($tmp,$dir.'/'.$storage))throw new RuntimeException('PDF konnte nicht gespeichert werden.');@chmod($dir.'/'.$storage,0640);$add->execute([$title,$date,trim((string)($_POST['note'][$i]??'')),$storage,basename((string)$name),$u['id']]);$count++;}if(!$count)throw new RuntimeException('Kein PDF ausgewählt.');flash('success',$count.' PDF(s) im Archiv gespeichert.');
  }
 }catch(Throwable $e){flash('danger',$e->getMessage());}redirect('/protokolle.php');
}
$detail=null;$items=[];$attendees=[];$audit=[];
if(isset($_GET['meeting'])){$q=$pdo->prepare("SELECT m.*,u.first_name,u.last_name FROM meetings m LEFT JOIN users u ON u.id=m.completed_by WHERE m.id=? AND m.status='completed'");$q->execute([(int)$_GET['meeting']]);$detail=$q->fetch();if(!$detail){http_response_code(404);exit('Protokoll nicht gefunden.');}$q=$pdo->prepare('SELECT a.*,u.first_name,u.last_name FROM meeting_agenda_items a LEFT JOIN users u ON u.id=a.updated_by WHERE a.meeting_id=? ORDER BY a.sort_order,a.id');$q->execute([$detail['id']]);$items=$q->fetchAll();$q=$pdo->prepare('SELECT u.first_name,u.last_name FROM meeting_attendees a JOIN users u ON u.id=a.user_id WHERE a.meeting_id=? ORDER BY u.last_name,u.first_name');$q->execute([$detail['id']]);$attendees=$q->fetchAll();if($canUpload){$q=$pdo->prepare('SELECT a.*,u.first_name,u.last_name FROM meeting_audit a LEFT JOIN users u ON u.id=a.user_id WHERE a.meeting_id=? ORDER BY a.id DESC');$q->execute([$detail['id']]);$audit=$q->fetchAll();}}
$meetings=$pdo->query("SELECT id,title,starts_at_utc,location,completed_at FROM meetings WHERE status='completed' ORDER BY starts_at_utc DESC,id DESC")->fetchAll();$documents=$pdo->query('SELECT * FROM protocol_documents ORDER BY document_date DESC,id DESC')->fetchAll();
$pageTitle='Protokolle';require __DIR__.'/includes/header.php';
?>
<div class="container dashboard-shell"><div class="row g-4"><?php require __DIR__.'/includes/sidebar.php';?><section class="col-lg-9">
<?php if($detail):?><a class="small" href="/protokolle.php">← Zum Archiv</a><div class="d-flex justify-content-between align-items-start gap-3 mt-3"><div><div class="eyebrow">Abgeschlossenes Protokoll</div><h1 class="section-title h2 mb-1"><?=e($detail['title'])?></h1><div class="text-secondary"><?=e(meeting_display($detail['starts_at_utc']))?> Uhr<?= $detail['location']?' · '.e($detail['location']):''?></div></div><?php if($canUpload):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="meeting_id" value="<?=$detail['id']?>"><button class="btn btn-outline-secondary" onclick="return confirm('Protokoll wieder öffnen?')">Wieder öffnen</button></form><?php endif;?></div><?php if($detail['note']):?><p class="text-secondary mt-3"><?=nl2br(e($detail['note']))?></p><?php endif;?><?php if($attendees):?><div class="panel p-3 mt-4"><strong>Anwesend:</strong> <?=e(implode(', ',array_map(fn($x)=>$x['first_name'].' '.$x['last_name'],$attendees)))?></div><?php endif;?><?php foreach($items as $n=>$item):?><article class="panel p-4 mt-3"><h2 class="h5"><?=$n+1?>. <?=e($item['title'])?></h2><?php if($item['protocol_html']):?><div class="news-body"><?=protocol_body_html($item['protocol_html'])?></div><?php else:?><p class="text-secondary mb-0">Kein Protokolleintrag.</p><?php endif;?></article><?php endforeach;?><?php if($canUpload&&$audit):?><details class="panel p-3 mt-4"><summary>Änderungshistorie</summary><?php foreach($audit as $a):?><div class="small border-top pt-2 mt-2"><?=e(date('d.m.Y H:i',strtotime($a['created_at'])))?> · <?=e($a['first_name'].' '.$a['last_name'])?> · <?=e($a['event'])?></div><?php endforeach;?></details><?php endif;?>
<?php else:?><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="eyebrow">Archiv</div><h1 class="section-title h2 mb-1">Protokolle</h1><p class="text-secondary mb-0">Abgeschlossene Stammtische und historische Dokumente.</p></div><?php if($canUpload):?><button class="btn btn-brand" data-bs-toggle="modal" data-bs-target="#upload">Historische PDFs hochladen</button><?php endif;?></div><div class="panel p-4 mb-4"><h2 class="h5">Stammtisch-Protokolle</h2><?php if($meetings):?><?php foreach($meetings as $m):?><a class="d-flex justify-content-between border-top py-3 text-decoration-none" href="/protokolle.php?meeting=<?=$m['id']?>"><span><strong><?=e($m['title'])?></strong><small class="d-block text-secondary"><?=e(meeting_display($m['starts_at_utc'],'d.m.Y'))?><?= $m['location']?' · '.e($m['location']):''?></small></span><i class="bi bi-chevron-right"></i></a><?php endforeach;?><?php else:?><p class="text-secondary mb-0">Noch keine abgeschlossenen Stammtische.</p><?php endif;?></div><div class="panel p-4"><h2 class="h5">Historische PDFs</h2><?php if($documents):?><?php foreach($documents as $d):?><a class="d-flex justify-content-between border-top py-3 text-decoration-none" href="/protocol-document.php?id=<?=$d['id']?>" target="_blank"><span><strong><?=e($d['title'])?></strong><small class="d-block text-secondary"><?=e(date('d.m.Y',strtotime($d['document_date'])))?><?= $d['note']?' · '.e($d['note']):''?></small></span><i class="bi bi-file-earmark-pdf"></i></a><?php endforeach;?><?php else:?><p class="text-secondary mb-0">Noch keine historischen PDFs hochgeladen.</p><?php endif;?></div><?php endif;?>
</section></div></div>
<?php if($canUpload&&!$detail):?><div class="modal fade" id="upload" tabindex="-1"><div class="modal-dialog"><form method="post" enctype="multipart/form-data" class="modal-content"><div class="modal-header"><h2 class="h5 mb-0">Historische PDFs</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="upload"><p class="small text-secondary">Mehrere PDFs auswählen und für jedes Dokument Titel, Datum und Bemerkung hinterlegen.</p><input id="pdfFiles" class="form-control mb-3" type="file" name="pdf[]" accept="application/pdf" multiple required><div id="pdfMeta"></div></div><div class="modal-footer"><button class="btn btn-brand">Hochladen</button></div></form></div></div><script>document.querySelector('#pdfFiles').onchange=e=>{let wrap=document.querySelector('#pdfMeta');wrap.innerHTML='';[...e.target.files].forEach((f,i)=>{let x=document.createElement('div');x.className='border-top pt-3 mt-3';x.innerHTML='<strong>'+f.name.replace(/[<>&]/g,'')+'</strong><input class="form-control mt-2" name="title[]" placeholder="Titel"><input class="form-control mt-2" type="date" name="date[]" required><input class="form-control mt-2" name="note[]" placeholder="Bemerkung (optional)">';wrap.append(x)})}</script><?php endif;?>
<?php require __DIR__.'/includes/footer.php'; ?>
