<?php
require_once __DIR__.'/includes/app.php';
$u=require_login(); $canCreate=can_create_meetings($pdo,$u); $canManage=can_manage_meetings($pdo,$u);
function sm_meeting(PDO $pdo,int $id): array {$q=$pdo->prepare('SELECT * FROM meetings WHERE id=?');$q->execute([$id]);$m=$q->fetch();if(!$m){http_response_code(404);exit('Stammtisch nicht gefunden.');}return $m;}
function sm_active(array $m): bool{return in_array($m['status'],['poll','scheduled'],true);}
function sm_push(PDO $pdo,string $title,string $body): void {send_push_to_all_active_users($pdo,$title,$body,'/stammtisch.php','meeting');}
function sm_order(PDO $pdo,int $meeting,array $ids): void {$q=$pdo->prepare('SELECT id,title FROM meeting_agenda_items WHERE meeting_id=?');$q->execute([$meeting]);$rows=$q->fetchAll();$valid=[];$last=[];foreach($rows as $row){if(mb_strtolower(trim($row['title']))==='sonstiges')$last[]=(int)$row['id'];else $valid[(int)$row['id']]=true;}$ids=array_values(array_filter($ids,fn($id)=>isset($valid[$id])));foreach(array_keys($valid) as $id)if(!in_array($id,$ids,true))$ids[]=$id;$ids=array_merge($ids,$last);$q=$pdo->prepare('UPDATE meeting_agenda_items SET sort_order=? WHERE meeting_id=? AND id=?');foreach($ids as $n=>$id)$q->execute([($n+1)*10,$meeting,$id]);}

if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='create'){
   if(!$canCreate)throw new RuntimeException('Nur Spieß, Zugführer, Kassierer oder Admin dürfen eine Terminfindung starten.');if(active_meeting($pdo))throw new RuntimeException('Es gibt bereits einen aktiven Stammtisch.');
   $title=trim((string)$_POST['title']);$dates=[];foreach((array)($_POST['date']??[]) as $i=>$d){if(trim((string)$d)==='')continue;$v=meeting_local_to_utc((string)$d,(string)(($_POST['time'][$i]??'')));if($v)$dates[$v]=true;}if(mb_strlen($title)<3||count($dates)<2)throw new RuntimeException('Überschrift und mindestens zwei unterschiedliche Terminoptionen sind erforderlich.');
   $pdo->beginTransaction();$q=$pdo->prepare("INSERT INTO meetings(title,status,location,note,created_by,updated_by) VALUES(?,'poll',?,?,?,?) RETURNING id");$q->execute([$title,trim((string)$_POST['location']),trim((string)$_POST['note']),$u['id'],$u['id']]);$id=(int)$q->fetchColumn();$q=$pdo->prepare('INSERT INTO meeting_poll_options(meeting_id,starts_at_utc) VALUES(?,?)');foreach(array_keys($dates) as $d)$q->execute([$id,$d]);meeting_audit($pdo,$id,$u['id'],'created','Terminfindung erstellt');$pdo->commit();sm_push($pdo,'Neue Stammtisch-Terminfindung',$title.' – jetzt abstimmen.');flash('success','Terminfindung erstellt.');
  } elseif($action==='vote'){
   $m=sm_meeting($pdo,(int)$_POST['meeting_id']);if($m['status']!=='poll')throw new RuntimeException('Die Terminfindung ist bereits beendet.');$q=$pdo->prepare('SELECT id FROM meeting_poll_options WHERE meeting_id=?');$q->execute([$m['id']]);$valid=array_flip(array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)));$ids=array_values(array_filter(array_unique(array_map('intval',(array)($_POST['options']??[]))),fn($x)=>isset($valid[$x])));$pdo->beginTransaction();$pdo->prepare('DELETE FROM meeting_votes WHERE user_id=? AND option_id IN(SELECT id FROM meeting_poll_options WHERE meeting_id=?)')->execute([$u['id'],$m['id']]);$q=$pdo->prepare('INSERT INTO meeting_votes(option_id,user_id) VALUES(?,?)');foreach($ids as $id)$q->execute([$id,$u['id']]);$pdo->commit();flash('success','Deine Stimmen wurden gespeichert.');
  } else {
   $m=sm_meeting($pdo,(int)($_POST['meeting_id']??0));
   if($action==='poll_update'){
    if(!$canManage||$m['status']!=='poll')throw new RuntimeException('Nur eine laufende Terminfindung kann geändert werden.');
    $title=trim((string)($_POST['title']??''));if(mb_strlen($title)<3)throw new RuntimeException('Überschrift ist erforderlich.');
    $q=$pdo->prepare('SELECT id,starts_at_utc FROM meeting_poll_options WHERE meeting_id=?');$q->execute([$m['id']]);$existing=[];foreach($q->fetchAll() as $row)$existing[(int)$row['id']]=$row['starts_at_utc'];
    $final=[];$update=[];$delete=[];
    foreach($existing as $oid=>$old){if(isset($_POST['opt_delete'][$oid])){$delete[]=$oid;continue;}$raw=(string)($_POST['opt_start'][$oid]??'');$v=meeting_local_to_utc(substr($raw,0,10),substr($raw,11,5));if(!$v)throw new RuntimeException('Ungültiger Termin.');$final[$oid]=$v;if($v!==$old)$update[$oid]=$v;}
    $add=[];foreach((array)($_POST['date']??[]) as $i=>$d){if(trim((string)$d)==='')continue;$v=meeting_local_to_utc((string)$d,(string)($_POST['time'][$i]??''));if($v)$add[$v]=true;}
    $all=array_merge(array_values($final),array_keys($add));if(count($all)!==count(array_unique($all)))throw new RuntimeException('Terminoptionen müssen unterschiedlich sein.');if(count($all)<2)throw new RuntimeException('Mindestens zwei Terminoptionen müssen bleiben.');
    $pdo->beginTransaction();
    $pdo->prepare('UPDATE meetings SET title=?,location=?,note=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$title,trim((string)($_POST['location']??'')),trim((string)($_POST['note']??'')),$u['id'],$m['id']]);
    $q=$pdo->prepare('DELETE FROM meeting_poll_options WHERE id=? AND meeting_id=?');foreach($delete as $oid)$q->execute([$oid,$m['id']]);
    $q=$pdo->prepare('UPDATE meeting_poll_options SET starts_at_utc=? WHERE id=? AND meeting_id=?');foreach($update as $oid=>$v)$q->execute([$v,$oid,$m['id']]);
    $q=$pdo->prepare('INSERT INTO meeting_poll_options(meeting_id,starts_at_utc) VALUES(?,?)');foreach(array_keys($add) as $v)$q->execute([$m['id'],$v]);
    meeting_audit($pdo,$m['id'],$u['id'],'poll_updated','Terminfindung geändert');$pdo->commit();
    if($delete||$update||$add)sm_push($pdo,'Stammtisch-Terminfindung geändert',$title.' – Terminoptionen wurden angepasst, bitte Auswahl prüfen.');
    flash('success','Terminfindung aktualisiert.');
   } elseif($action==='schedule'){
    if(!$canCreate||$m['status']!=='poll')throw new RuntimeException('Termin kann nicht festgelegt werden.');$q=$pdo->prepare('SELECT starts_at_utc FROM meeting_poll_options WHERE id=? AND meeting_id=?');$q->execute([(int)$_POST['option'],$m['id']]);$date=$q->fetchColumn();if(!$date)throw new RuntimeException('Terminoption nicht gefunden.');$pdo->beginTransaction();$pdo->prepare("UPDATE meetings SET status='scheduled',starts_at_utc=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$date,$u['id'],$m['id']]);$q=$pdo->prepare('INSERT INTO meeting_agenda_items(meeting_id,title,sort_order,updated_by) VALUES(?,?,?,?)');$q->execute([$m['id'],'Kassenstand',10,$u['id']]);$q->execute([$m['id'],'Sonstiges',20,$u['id']]);meeting_audit($pdo,$m['id'],$u['id'],'scheduled','Termin festgelegt');$pdo->commit();sm_push($pdo,'Stammtisch festgelegt',$m['title'].' · '.meeting_display($date));flash('success','Termin festgelegt.');
   } elseif($action==='delete_poll'){
    if(!$canManage||$m['status']!=='poll')throw new RuntimeException('Nur eine laufende Terminfindung darf gelöscht werden.');$pdo->prepare('DELETE FROM meetings WHERE id=?')->execute([$m['id']]);flash('success','Terminfindung gelöscht.');
   } elseif($action==='cancel'){
    if(!$canManage||$m['status']!=='scheduled')throw new RuntimeException('Nur ein festgelegter Termin kann abgesagt werden.');$pdo->prepare("UPDATE meetings SET status='cancelled',updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$u['id'],$m['id']]);meeting_audit($pdo,$m['id'],$u['id'],'cancelled','Abgesagt');sm_push($pdo,'Stammtisch abgesagt',$m['title'].' findet nicht statt.');flash('success','Stammtisch abgesagt.');
   } elseif($action==='suggest'){
    if($m['status']!=='scheduled')throw new RuntimeException('Themen können nur für einen festgelegten Stammtisch vorgeschlagen werden.');$title=trim((string)$_POST['title']);if(mb_strlen($title)<3)throw new RuntimeException('Bitte ein Thema angeben.');$pdo->prepare('INSERT INTO meeting_topic_suggestions(meeting_id,title,note,suggested_by) VALUES(?,?,?,?)')->execute([$m['id'],$title,trim((string)$_POST['note']),$u['id']]);flash('success','Thema vorgeschlagen.');
   } else {
    $reopen=$action==='reopen';if($reopen){if(!can_reopen_protocols()||$m['status']!=='completed')throw new RuntimeException('Nur Schriftführer oder Admin dürfen ein abgeschlossenes Protokoll öffnen.');$pdo->prepare("UPDATE meetings SET status='scheduled',completed_at=NULL,completed_by=NULL,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$u['id'],$m['id']]);meeting_audit($pdo,$m['id'],$u['id'],'reopened','Protokoll wieder geöffnet');flash('success','Protokoll wieder geöffnet.');}
    else {if(!$canManage||!sm_active($m))throw new RuntimeException('Keine Berechtigung oder Protokoll abgeschlossen.');
     if($action==='details'){$title=trim((string)$_POST['title']);$date=meeting_local_to_utc(substr((string)$_POST['starts_at'],0,10),substr((string)$_POST['starts_at'],11,5));if(mb_strlen($title)<3||!$date)throw new RuntimeException('Überschrift und Termin sind erforderlich.');$changed=$date!==$m['starts_at_utc'];$pdo->prepare('UPDATE meetings SET title=?,starts_at_utc=?,location=?,note=?,updated_by=?,updated_at=CURRENT_TIMESTAMP,reminder_sent_at=NULL WHERE id=?')->execute([$title,$date,trim((string)$_POST['location']),trim((string)$_POST['note']),$u['id'],$m['id']]);meeting_audit($pdo,$m['id'],$u['id'],'details_updated',$changed?'Termin geändert':null);if($changed)sm_push($pdo,'Stammtisch-Termin geändert',$title.' · '.meeting_display($date));flash('success','Details gespeichert.');}
     elseif($action==='agenda_add'){$title=trim((string)$_POST['title']);if(mb_strlen($title)<2)throw new RuntimeException('TOP benennen.');$q=$pdo->prepare('SELECT COALESCE(MAX(sort_order),0) FROM meeting_agenda_items WHERE meeting_id=?');$q->execute([$m['id']]);$pdo->prepare('INSERT INTO meeting_agenda_items(meeting_id,title,sort_order,updated_by) VALUES(?,?,?,?)')->execute([$m['id'],$title,(int)$q->fetchColumn()+10,$u['id']]);flash('success','TOP hinzugefügt.');}
     elseif($action==='agenda_delete'){$pdo->prepare('DELETE FROM meeting_agenda_items WHERE id=? AND meeting_id=?')->execute([(int)$_POST['item_id'],$m['id']]);flash('success','TOP gelöscht.');}
     elseif($action==='agenda_order'){$ids=array_filter(array_map('intval',explode(',',(string)$_POST['order'])));sm_order($pdo,$m['id'],$ids);flash('success','Reihenfolge gespeichert.');}
     elseif($action==='suggestion'){$q=$pdo->prepare("SELECT * FROM meeting_topic_suggestions WHERE id=? AND meeting_id=? AND status='pending'");$q->execute([(int)$_POST['suggestion_id'],$m['id']]);$s=$q->fetch();if(!$s)throw new RuntimeException('Vorschlag nicht gefunden.');$accept=$_POST['decision']==='accept';$pdo->prepare('UPDATE meeting_topic_suggestions SET status=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$accept?'accepted':'rejected',$u['id'],$s['id']]);if($accept){$q=$pdo->prepare('SELECT COALESCE(MAX(sort_order),0) FROM meeting_agenda_items WHERE meeting_id=?');$q->execute([$m['id']]);$pdo->prepare('INSERT INTO meeting_agenda_items(meeting_id,title,sort_order,updated_by) VALUES(?,?,?,?)')->execute([$m['id'],$s['title'],(int)$q->fetchColumn()+10,$u['id']]);}flash('success',$accept?'Thema übernommen.':'Vorschlag abgelehnt.');}
     elseif($action==='attendees'){$ids=array_unique(array_map('intval',(array)($_POST['attendees']??[])));$pdo->beginTransaction();$pdo->prepare('DELETE FROM meeting_attendees WHERE meeting_id=?')->execute([$m['id']]);$q=$pdo->prepare('INSERT INTO meeting_attendees(meeting_id,user_id,updated_by) SELECT ?,id,? FROM users WHERE id=? AND is_active=1');foreach($ids as $id)$q->execute([$m['id'],$u['id'],$id]);$pdo->commit();flash('success','Anwesenheit gespeichert.');}
     elseif($action==='protocol'){$html=protocol_sanitize_html((string)$_POST['html']);$pdo->prepare('UPDATE meeting_agenda_items SET protocol_html=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND meeting_id=?')->execute([$html,$u['id'],(int)$_POST['item_id'],$m['id']]);flash('success','Protokoll gespeichert.');}
     elseif($action==='complete'){if($_POST['confirm']!=='abschluss')throw new RuntimeException('Sicherheitsabfrage nicht bestätigt.');$pdo->prepare("UPDATE meetings SET status='completed',completed_at=CURRENT_TIMESTAMP,completed_by=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$u['id'],$u['id'],$m['id']]);meeting_audit($pdo,$m['id'],$u['id'],'completed','Abgeschlossen');flash('success','Stammtisch abgeschlossen und Protokoll eingefroren.');}
     else throw new RuntimeException('Unbekannte Aktion.');
    }
   }
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger',$e->getMessage());}
 redirect('/stammtisch.php');
}
$m=active_meeting($pdo);$options=$agenda=$suggestions=$members=[];$present=[];$myVotes=[];
if($m){$q=$pdo->prepare("SELECT o.id,o.starts_at_utc,COUNT(v.user_id) votes,string_agg(TRIM(u.first_name||' '||u.last_name),', ' ORDER BY u.last_name,u.first_name) voters FROM meeting_poll_options o LEFT JOIN meeting_votes v ON v.option_id=o.id LEFT JOIN users u ON u.id=v.user_id WHERE o.meeting_id=? GROUP BY o.id ORDER BY o.starts_at_utc");$q->execute([$m['id']]);$options=$q->fetchAll();if($m['status']==='poll'){$q=$pdo->prepare('SELECT v.option_id FROM meeting_votes v JOIN meeting_poll_options o ON o.id=v.option_id WHERE o.meeting_id=? AND v.user_id=?');$q->execute([$m['id'],$u['id']]);$myVotes=array_flip(array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)));}$q=$pdo->prepare('SELECT a.*,u.first_name,u.last_name FROM meeting_agenda_items a LEFT JOIN users u ON u.id=a.updated_by WHERE a.meeting_id=? ORDER BY a.sort_order,a.id');$q->execute([$m['id']]);$agenda=$q->fetchAll();$q=$pdo->prepare("SELECT s.*,u.first_name,u.last_name FROM meeting_topic_suggestions s JOIN users u ON u.id=s.suggested_by WHERE s.meeting_id=? AND s.status='pending' ORDER BY s.id");$q->execute([$m['id']]);$suggestions=$q->fetchAll();if($canManage){$members=$pdo->query('SELECT id,first_name,last_name FROM users WHERE is_active=1 ORDER BY last_name,first_name')->fetchAll();$q=$pdo->prepare('SELECT user_id FROM meeting_attendees WHERE meeting_id=?');$q->execute([$m['id']]);$present=array_flip(array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)));}}
$pageTitle='Stammtisch';require __DIR__.'/includes/header.php';
?>
<div class="container dashboard-shell"><div class="row g-4"><?php require __DIR__.'/includes/sidebar.php';?><section class="col-lg-9">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="eyebrow">Organisation</div><h1 class="section-title h2 mb-1">Stammtisch</h1><p class="text-secondary mb-0">Terminfindung, Tagesordnung und Protokoll.</p></div><?php if($canCreate&&!$m):?><button class="btn btn-brand" data-bs-toggle="modal" data-bs-target="#create">Terminfindung starten</button><?php endif;?></div>
<?php if(!$m):?><div class="panel p-5 text-center"><div class="fs-1">🍻</div><h2 class="h5 mt-3">Kein Stammtisch aktiv</h2><p class="text-secondary mb-0">Sobald einer angelegt wird, erscheint er hier.</p></div><?php else:?>
<div class="panel p-4 mb-4"><div class="d-flex justify-content-between gap-3"><div><div class="eyebrow"><?= $m['status']==='poll'?'Terminfindung':'Termin festgelegt'?></div><h2 class="h3 mb-1"><?=e($m['title'])?></h2><?php if($m['status']==='scheduled'):?><div class="fw-semibold">📅 <?=e(meeting_display($m['starts_at_utc']))?> Uhr</div><div class="text-secondary"><?=e($m['location'])?></div><?php endif;?><?php if($m['note']):?><div class="text-secondary mt-2"><?=nl2br(e($m['note']))?></div><?php endif;?></div><?php if($canManage&&$m['status']==='poll'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_poll"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Terminfindung löschen?')">Löschen</button></form><?php endif;?></div></div>
<?php if($m['status']==='poll'):?><div class="panel p-4 mb-4"><h2 class="h5">Deine Terminwahl</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="vote"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><?php foreach($options as $o):?><label class="form-check border rounded p-3 mb-2"><input class="form-check-input" type="checkbox" name="options[]" value="<?=$o['id']?>" <?=isset($myVotes[(int)$o['id']])?'checked':''?>><span class="ms-1"><strong><?=e(meeting_display($o['starts_at_utc']))?> Uhr</strong><small class="d-block text-secondary"><?=$o['votes']?> Stimmen<?= $o['voters']?' · '.e($o['voters']):''?></small></span></label><?php endforeach;?><button class="btn btn-brand">Stimmen speichern</button><small class="d-block text-secondary mt-2">Mehrfachwahl möglich; Stimmen und Namen sind für alle sichtbar.</small></form></div><?php if($canManage):?><div class="panel p-4 mb-4"><h2 class="h5">Terminfindung bearbeiten</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="poll_update"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><div class="col-12"><input class="form-control" name="title" value="<?=e($m['title'])?>" required></div><div class="col-md-6"><input class="form-control" name="location" value="<?=e($m['location'])?>" placeholder="Ort"></div><div class="col-md-6"><input class="form-control" name="note" value="<?=e($m['note'])?>" placeholder="Bemerkung"></div><div class="col-12 mt-3"><strong>Terminoptionen</strong><small class="d-block text-secondary mb-2">Änderungen an bestehenden Optionen behalten die Stimmen; entfernte Optionen verlieren ihre Stimmen. Mindestens zwei Optionen.</small></div><?php foreach($options as $o):?><div class="col-12"><div class="row g-2 align-items-center"><div class="col-8 col-md-6"><input class="form-control" type="datetime-local" name="opt_start[<?=$o['id']?>]" value="<?=e(meeting_local_input($o['starts_at_utc']))?>" required></div><div class="col-4 col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" name="opt_delete[<?=$o['id']?>]" value="1"> entfernen (<?=$o['votes']?> Stimmen)</label></div></div></div><?php endforeach;?><div class="col-12 mt-2"><small class="text-secondary">Weitere Optionen hinzufügen:</small></div><?php for($i=0;$i<2;$i++):?><div class="col-7 col-md-4"><input type="date" class="form-control" name="date[]"></div><div class="col-5 col-md-2"><input type="time" class="form-control" name="time[]" value="19:30"></div><?php endfor;?><div class="col-12"><button class="btn btn-outline-secondary">Änderungen speichern</button></div></form></div><?php endif;?>
<?php if($canCreate):?><div class="panel p-4"><h2 class="h5">Termin festlegen</h2><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="schedule"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><select class="form-select" name="option"><?php foreach($options as $o):?><option value="<?=$o['id']?>"><?=e(meeting_display($o['starts_at_utc'],'D, d.m. H:i'))?> Uhr · <?=$o['votes']?> Stimmen</option><?php endforeach;?></select><button class="btn btn-brand" onclick="return confirm('Termin wirklich festlegen?')">Festlegen</button></form></div><?php endif;?>
<?php else:?>
<?php if($canManage):?><div class="panel p-4 mb-4"><h2 class="h5">Termin bearbeiten</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="details"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><div class="col-md-6"><input class="form-control" name="title" value="<?=e($m['title'])?>" required></div><div class="col-md-6"><input class="form-control" type="datetime-local" name="starts_at" value="<?=e(meeting_local_input($m['starts_at_utc']))?>" required></div><div class="col-md-6"><input class="form-control" name="location" value="<?=e($m['location'])?>" placeholder="Ort"></div><div class="col-md-6"><input class="form-control" name="note" value="<?=e($m['note'])?>" placeholder="Bemerkung"></div><div><button class="btn btn-outline-secondary">Speichern</button></div></form></div><?php endif;?>
<div class="panel p-4 mb-4"><div class="d-flex justify-content-between gap-3 mb-3"><div><h2 class="h5 mb-0">Tagesordnung</h2><small class="text-secondary">TOPs per Ziehen sortieren.</small></div><?php if($canManage):?><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="agenda_add"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input class="form-control form-control-sm" name="title" placeholder="Neuer TOP"><button class="btn btn-sm btn-brand">+</button></form><?php endif;?></div><div id="agenda" data-sortable><?php foreach($agenda as $n=>$a):?><article class="border rounded p-3 mb-2" data-id="<?=$a['id']?>" draggable="<?=$canManage?'true':'false'?>"><div class="d-flex gap-2"><i class="bi bi-grip-vertical"></i><div class="flex-grow-1"><strong><?=$n+1?>. <?=e($a['title'])?></strong><?php if($a['updated_by']):?><small class="d-block text-secondary">Zuletzt bearbeitet von <?=e($a['first_name'].' '.$a['last_name'])?> · <?=e(date('d.m.Y H:i',strtotime($a['updated_at'])))?> Uhr</small><?php endif;?></div><?php if($canManage):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="agenda_delete"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input type="hidden" name="item_id" value="<?=$a['id']?>"><button class="btn btn-sm btn-outline-danger">Löschen</button></form><?php endif;?></div><?php if($canManage):?><form class="protocol-editor mt-3" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="protocol"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input type="hidden" name="item_id" value="<?=$a['id']?>"><div class="wysiwyg-toolbar"><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="insertUnorderedList">•</button><button type="button" data-image>Bild</button><input type="file" accept="image/jpeg,image/png,image/webp" hidden></div><div class="wysiwyg-editor" contenteditable="true"><?=protocol_body_html($a['protocol_html'])?></div><textarea name="html" hidden></textarea><button class="btn btn-sm btn-outline-secondary mt-2">Protokoll speichern</button></form><?php elseif($a['protocol_html']):?><div class="news-body mt-3"><?=protocol_body_html($a['protocol_html'])?></div><?php endif;?></article><?php endforeach;?></div><?php if($canManage):?><form method="post" id="order"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="agenda_order"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input type="hidden" name="order"><button class="btn btn-sm btn-outline-secondary">Reihenfolge speichern</button></form><?php endif;?></div>
<div class="row g-4"><div class="col-md-6"><div class="panel p-4 h-100"><h2 class="h5">Thema vorschlagen</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="suggest"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input class="form-control mb-2" name="title" placeholder="Thema" required><textarea class="form-control mb-2" name="note" placeholder="Optionaler Hinweis"></textarea><button class="btn btn-outline-secondary">Vorschlagen</button></form><?php if($canManage&&$suggestions):?><hr><?php foreach($suggestions as $s):?><div class="border-top py-2"><strong><?=e($s['title'])?></strong><small class="d-block text-secondary">von <?=e($s['first_name'].' '.$s['last_name'])?></small><form method="post" class="mt-1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="suggestion"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input type="hidden" name="suggestion_id" value="<?=$s['id']?>"><button class="btn btn-sm btn-outline-success" name="decision" value="accept">Übernehmen</button><button class="btn btn-sm btn-outline-danger" name="decision" value="reject">Ablehnen</button></form></div><?php endforeach;?><?php endif;?></div></div><?php if($canManage):?><div class="col-md-6"><div class="panel p-4 h-100"><h2 class="h5">Anwesenheit</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="attendees"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><div class="meeting-attendees"><?php foreach($members as $x):?><label class="form-check"><input class="form-check-input" type="checkbox" name="attendees[]" value="<?=$x['id']?>" <?=isset($present[$x['id']])?'checked':''?>> <?=e($x['first_name'].' '.$x['last_name'])?></label><?php endforeach;?></div><button class="btn btn-outline-secondary mt-3">Speichern</button></form></div></div><?php endif;?></div>
<?php if($canManage):?><div class="d-flex gap-2 mt-4"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="complete"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><input type="hidden" name="confirm" value="abschluss"><button class="btn btn-brand" onclick="return confirm('Stammtisch wirklich abschließen? Das Protokoll wird eingefroren.')">Abschließen</button></form><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="meeting_id" value="<?=$m['id']?>"><button class="btn btn-outline-danger" onclick="return confirm('Stammtisch absagen?')">Absagen</button></form></div><?php endif;?>
<?php endif;?><?php endif;?></section></div></div>
<?php if($canCreate&&!$m):?><div class="modal fade" id="create" tabindex="-1"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5 mb-0">Terminfindung starten</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><input class="form-control mb-3" name="title" value="Stammtisch" required><?php for($i=0;$i<3;$i++):?><div class="row g-2 mb-2"><div class="col-7"><input type="date" class="form-control" name="date[]" <?=$i<2?'required':''?>></div><div class="col-5"><input type="time" class="form-control" name="time[]" value="19:30" <?=$i<2?'required':''?>></div></div><?php endfor;?><input class="form-control mt-3" name="location" placeholder="Ort (optional)"><textarea class="form-control mt-2" name="note" placeholder="Bemerkung (optional)"></textarea></div><div class="modal-footer"><button class="btn btn-brand">Veröffentlichen</button></div></form></div></div><?php endif;?>
<script>document.querySelectorAll('.protocol-editor').forEach(f=>{let e=f.querySelector('.wysiwyg-editor'),o=f.querySelector('textarea'),i=f.querySelector('input[type=file]');f.onsubmit=()=>o.value=e.innerHTML;f.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{e.focus();document.execCommand(b.dataset.cmd,false,null)});f.querySelector('[data-image]').onclick=()=>i.click();i.onchange=async()=>{let d=new FormData();d.append('csrf','<?=e(csrf_token())?>');d.append('meeting_id','<?=$m['id']??0?>');d.append('image',i.files[0]);let r=await fetch('/meeting-image-upload.php',{method:'POST',body:d}),j=await r.json();if(!r.ok||!j.ok)return alert(j.error||'Upload fehlgeschlagen');e.focus();document.execCommand('insertImage',false,j.url)}});let l=document.querySelector('[data-sortable]'),drag;if(l){l.querySelectorAll('[draggable=true]').forEach(x=>{x.ondragstart=()=>drag=x;x.ondragover=e=>{e.preventDefault();if(drag&&drag!==x)l.insertBefore(drag,e.clientY<x.getBoundingClientRect().top+x.offsetHeight/2?x:x.nextSibling)}});let f=document.querySelector('#order');if(f)f.onsubmit=()=>f.querySelector('[name=order]').value=[...l.children].map(x=>x.dataset.id).join(',')}</script>
<?php require __DIR__.'/includes/footer.php'; ?>
